### ISSUE TITLE
Cannot import SerialED

### ISSUE THREAD

**Issue by AEljarrat** [stefsmeets/problematic#1]
After a succesful installation, following the instructions in the tutorial, I get an ImportError when trying to import `SerialED`. It seems the error stems from routines in `pyxem.utils.peakfinders2D` being changes. Looking at the `pyxem` Issue tracker it seems this is a known issue. Nevertheless, since I am interested in trying your `problematic` code, I want to ask if there is any fix or workaround to this problem? 
Many thanks!

PS. error trace:
``` python 
from problematic import Indexer, Projector

from problematic import serialED

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-8a00391d9d08> in <module>()
      1 from problematic import Indexer, Projector
----> 2 from problematic import serialED

~/anaconda3/envs/pyxem/lib/python3.6/site-packages/problematic/serialED.py in <module>()
      2 import hyperspy.api as hs
      3 from hdf5_to_hyperspy import hdf5_to_hyperspy
----> 4 from pyxem.utils.peakfinders2D import find_peaks_regionprops
      5 from pyxem.utils.expt_utils import find_beam_position_blur
      6 import os, sys

ImportError: cannot import name 'find_peaks_regionprops'
```

**Comment by stefsmeets** [comment]
Hi @AEljarrat, thank you for the report. I just pushed a commit (0f9057a3baa29fea2be52e11cb55105e2ddefe7d) from a branch that I was working on a few months ago that removes the `pyxem` dependency, and uses `hyperspy` directly instead. As I'm not actively working on the code at the moment, and `pyxem` is changing quite rapidly, perhaps this was a good time to do so. Could you check if it works for you?

**Comment by AEljarrat** [comment]
Yes, it works now! I upgraded my installation and I am now able to load `serialD`. Thanks a lot for the update.

**Comment by stefsmeets** [comment]
Good to know! Thanks for testing it out!
