### ISSUE TITLE
sginfo problem?

### ISSUE THREAD

**Issue by MichielDeKock** [stefsmeets/problematic#2]
I am primarily interested in the indexer, but when I create the object the error,
SpaceGroupError: No such space group 'Fd-3m',
occurs, which is caused by the second call to SgInfo in parse_sginfo.parse with the argument '-Conditions'.  As [SgInfo](cci.lbl.gov/sginfo/) does not have that option, I assume I am missing something obvious?
The error trace is: 
```---------------------------------------------------------------------------
SpaceGroupError                           Traceback (most recent call last)
<ipython-input-3-7897c2c4bcb4> in <module>()
      6 spgr = 'Fd-3m'            # space group
      7 projector = Projector.from_parameters(params, spgr=spgr, name=name, 
----> 8                                       dmin=dmin, dmax=dmax, thickness=thickness)
      9 indexer = Indexer.from_projector(projector, pixelsize=pixelsize)

~/anaconda3/lib/python3.6/site-packages/problematic-0.1.0-py3.6-linux-x86_64.egg/problematic/projector.py in from_parameters(cls, params, spgr, name, composition, **kwargs)
    208 
    209         See: xcore.unitcell.UnitCell"""
--> 210         return cls(UnitCell(params, spgr=spgr, name=name, composition=composition), **kwargs)
    211 
    212     def to_dict(self):

~/anaconda3/lib/python3.6/site-packages/problematic-0.1.0-py3.6-linux-x86_64.egg/problematic/unitcell.py in __init__(self, cell_params, spgr, name, composition)
     44             self.__dict__.update(spgr.__dict__)
     45         else:
---> 46             super(UnitCell, self).__init__(spgr)
     47 
     48         self.name = name

~/anaconda3/lib/python3.6/site-packages/problematic-0.1.0-py3.6-linux-x86_64.egg/problematic/spacegroup.py in __init__(self, symbol)
    506         from parse_sginfo import parse
    507 
--> 508         dct = parse(symbol)
    509 
    510         self._dct = dct

~/anaconda3/lib/python3.6/site-packages/problematic-0.1.0-py3.6-linux-x86_64.egg/problematic/parse_sginfo.py in parse(spgr, verbose)
    116 
    117         if line.startswith("sginfo: Error: Unknown Space Group Symbol"):
--> 118             raise SpaceGroupError(f"No such space group '{spgr}'")
    119 
    120         if line.startswith("Reflection conditions"):

SpaceGroupError: No such space group 'Fd-3m'```

**Comment by stefsmeets** [comment]
Hi Michiel,

It could indeed be that this is a problem with your sginfo that is outdated. Can you confirm that when you type `sginfo Fd-3m -Conditions` in the terminal that it gives the error `sginfo: Error: Unknown Space Group Symbol`? If so, where did you obtain your copy of `sginfo`? It may be that you are using a very old version if it does not have the `-Conditions` flag.

I have an up to date version for linux (compiled on debian) included in here: [focus-package_linux_2018-03-09.tar.gz](https://github.com/stefsmeets/focus_package/releases/download/v2.3/focus-package_linux_2018-03-09.tar.gz) (in the `bin_linux` directory). You can also try to compile it yourself: https://github.com/stefsmeets/focus_package/tree/master/focus/src/sginfo

**Comment by MichielDeKock** [comment]
Thanks Stef,

The newer version of ```sginfo``` solved the problem and ```sginfo Fd-3m -Conditions``` does not give an error anymore.
