### ISSUE TITLE
Fd-3m space group

### ISSUE THREAD

**Issue by Taimin** [stefsmeets/problematic#4]
Hi Stef, I found sginfo will output Fd-3m space group as "Fd-3m:1". Subsequently, problematic will consider the self.settings=1 and trying to find laue symmetry operation "m-3m:1" in laue_symops.py, in which it doesn't exist. Subsequently, an error will occur when trying to follow the indexing_template as KeyError.

Do you know if there are other laue symmetry operation for "m-3m"? Or the settings should be limited to ('a', 'b', 'c')?

**Comment by stefsmeets** [comment]
Hi Taimin, good question! The Laue group will be the same, it is just that `Fd-3m` has two possible origins. For `Fd-3m` the inversion center is not on the origin, so another inversion operation has to be applied.

This means you can drop the `:1` / `:2` from the search string.

**Comment by Taimin** [comment]
Great! Then I will drop it.
